### PR TITLE
Fix typo on formatter 'webvtt'

### LINKED ISSUE #134: Get confused at the format "webvvt"
I thought this might be a typo?

https://github.com/jdepoix/youtube-transcript-api/blob/5657a4867476d6edae582b7de3a07e395128b964/youtube_transcript_api/formatters.py#L138-L144

REF: [Web Video Text Tracks Format (WebVTT)](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API)

### LINKED ISSUE #138: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /watch?
Hello,
I am using youtube-transcript-api and this error is thrown from time to time.
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /watch?v=N1pseW9waNI (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2148e536d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))`

I've also added a time.sleep(2.4) (politeness delay of 2.4s between two requests) but this doesn't solve the problem.
PS: When I get the error, I wait approx. 20mn and I send the request, it works, and just after, the error thrown, and so forth..

The line producing the error is : `transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)`

Whole ERROR logs: 

[logs.txt](https://github.com/jdepoix/youtube-transcript-api/files/7648869/logs.txt)

Your help is appreciated ! :-)) thanks

### PR DESCRIPTION
**Pull request by MAJA-Lin**
Resolve #134

### CODE REVIEW

**Comment by jdepoix** [comment]
The python 2.7 builds have recently started failing although there were no changes. I will have to look into this when I have a bit more time at hand 🤔

**Comment by MAJA-Lin** [comment]
Sure. Thanks for the review.

**Review by jdepoix — APPROVED** [review]

**Comment by jdepoix** [comment]
Hi @MAJA-Lin,
thanks for your PR and sorry for the wait!

Although I was able to run the test suite locally with python 2.7 without a problem, I wasn't able to figure out what made them fail on Travis. However, since python 2.7 is no longer supported I just dropped its support and removed it from the build plan. I merged those changes into master, therefore you should be able to fix your build by merging master into yours.

**Comment by MAJA-Lin** [comment]
Hi @jdepoix,
thanks for the build changes.

The testing result seems good after I merged from the master.
I'll just merge this pull request.
Thanks for the help again!

**Pull request merged**
