### PR TITLE
Assert types

### LINKED ISSUE #125: Add assert to get_transcripts to check if it is a string
There have been a few issues like #124 where people mistakingly use `get_transcripts` instead of `get_transcript` and pass in a string. This does not a fail as a string is an iterable, but does not yield the desired result.

This mistake could be made more obvious by adding an assert to `get_transcripts` checking if the param is a string.

### PR DESCRIPTION
**Pull request by majamil16**
Added an assert statement in get_transcripts / get_transcript to check if input is of the expected type - closes #125

### CODE REVIEW

**Comment by jdepoix** [comment]
Hi @majamil16, thank you very much for your contribution! I have been postponing this forever, so this is very much appreciated!

However, for some reason the travis builds are not triggered automatically. I just did a quick check and couldn't figure out why, so I will have to put in a bit more time to get this fixed before being able to merge this.

**Comment by majamil16** [comment]
@jdepoix sure thing! Let me know if there's anything I can help with.

**Comment by jdepoix** [comment]
Hi @majamil16,
sorry for the late merge. I have been really busy lately and forgot about this PR still being open to be honest 🙈 
I fixed the builds and merged it now. I expect another PR to be merged soon and will release them together in v0.5.0.
Thank you very much for your contribution! 😊 👍

**Comment by jdepoix** [comment]
Released in [v0.5.0](https://github.com/jdepoix/youtube-transcript-api/releases/tag/v0.5.0)! 🥳 
Thank you very much for you contribution @majamil16 ! 😊

**Pull request merged**
