### PR TITLE
Remove unused code for translation languages in TranscriptList constructor

### PR DESCRIPTION
**Pull request by ahmedJaafari**
For videos without Translation (new YouTube version) it always raises an error.

### CODE REVIEW

**Comment by jdepoix** [comment]
Hi @ahmedJaafari, could you please elaborate on what exactly is failing? I don't know about new YouTube, could you share a link?

Either way, you can't simply remove the initialization and always initialize with an empty list, as this will break a lot of code (as well as the test suite) depending on this list being populated. If there actually is a problem caused by a new version of YouTube, we will have to find a different solution.

**Comment by 0xRaduan** [comment]
hey, @jdepoix, there is an issue with what seems like a new format.

example video which results in KeyError on `'translationLanguages'`: https://www.youtube.com/watch?v=KUnclLt2RqQ

Could you please advise on how to hotfix it? I initially thought it's for non-english videos, but seems like it is failing more often, than I initially anticipated.

**Comment by jdepoix** [comment]
Hey @0xRaduan, could you please elaborate which code you are executing to cause this error? I cannot replicate this. If I run `YouTubeTranscriptApi.get_transcript("KUnclLt2RqQ")` I don't get an `KeyError` and I get the full list of translation languages.

**Comment by 0xRaduan** [comment]
fair, @jdepoix – seems like a temporary problem on my side, I am not facing problems with `KUnclLt2RqQ` anymore.

**Comment by jdepoix** [comment]
Okay, I will close this PR then. If you encounter the problem again open an issue and then we can discuss a potential solution.

**Pull request closed without merging**
